name: hello-world
on:
  push
jobs:
  build-test:
    uses: dosky-dev/ghas_test/.github/workflows/baseflow.yml@dev
    with:
      node-version: '18.x'
      OS: ubuntu-latest

  deploy:
      needs: build-test
      runs-on: ubuntu-latest
      permissions:
        contents: write
        pages: write
        id-token: write
      environment:
        name: production
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Checkout the code repository
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN}}
        - name: set up node js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        - name: configure GH pages
          uses: actions/configure-pages@v3
          with:
            static_site_generator: next
        - run: npm install
        - run: npm run build
        - name: upload artifacts
          uses: actions/upload-pages-artifact@v1
          with:
            path: "./out"
        - name: deploy
          id: deployment
          uses: actions/deploy-pages@v1
      

